### ISSUE TITLE
Allow extend vote without any maps

### ISSUE THREAD

**Issue by skyprah** [ssypchenko/GG1MapChooser#3]
Hi,

Some suggestions

Can you please allow extend vote with 0 maps in the vote. After testing I found the menu did not appear if maps was set to none.
Preferably also a user command to initiate a extend vote or chat method requiring X% of users to type the !ve command in chat (same as rtv method)

Thanks

**Comment by ssypchenko** [comment]
Hi, The idea of this plugin is to change maps most effectively. There is a much more effective way  to change one cvar - do it in a console. Or you may use any voting plugin.
