### ISSUE TITLE
TIP

### ISSUE THREAD

**Issue by chycken** [ssypchenko/GG1MapChooser#6]
Hi!
First of all: thanks for your working!
Could you please add a timeleft/!timeleft command to the plugin? It would be very cool.
I don't know how well you know the wasd api developer, but it would be nice if you could talk to him so that "space" is the selection instead of the letter D. Thanks!

**Comment by ssypchenko** [comment]
I replaced D to Space in v 1.5.0 for players in teams. Spectators still have to use D, unfortunately. 
timeleft is not a very obvious command. I have it in mind for future development, but it is not easy.
